Fix: Avoid exception when window is None
Some open files (maybe without project), would otherwise occasionally raise the following exception in console:

  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/common/util/view.py", line 72, in refresh_gitsavvy
    view.window().run_command("refresh_folder_list")
AttributeError: 'NoneType' object has no attribute 'run_command'