Fix: check if the current dashboard is on the list
The following error occurs if `tab_order` is set as
```
    "tab_order": ["status", "rebase", "graph"]
```
and <kbd>tab</kbd> is prssed on the Branch dashboard.

```
Traceback (most recent call last):
  File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 28, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(source, target, reverse))
  File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 31, in run_async
    to_load = target or self.get_next(source, reverse)
  File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 47, in get_next
    source_idx = tab_order.index(source)
ValueError: 'branch' is not in list
```

It is becaused the `branch_view` is not in `tab_order`.